developing
hguzman/ADSO2558427 pull request #28
Opened 2022-09-14 03:59 UTC by Luisafernanda29

good evening, this is to give you information about my contribution to the repository, I hope you take it into account.

2022-09-15 12:37 UTC, LonelyWalker17 requested changes

2022-09-15 12:37 UTC, LonelyWalker17 commented on luisa_cortezano/ejercicio.md
> +Sub recolecta()
Please check your code, variables aren't initialized like this. You must initialize variables like this: tr = 0, sb = 0, and so on.

2022-09-15 12:37 UTC, LonelyWalker17 commented on luisa_cortezano/ejercicio2.md
> +    While sw
The limit variable must be in true so that you can end the loop. If not, the code will run infinitely.

2022-09-15 14:18 UTC, LonelyWalker17 requested changes
Please @Luisafernanda29 edit your flowchart. You still need to indicate which of the addresses the program is going to address if the loop is true.

2022-09-18 00:08 UTC, LonelyWalker17 approved these changes

2022-09-18 04:39 UTC, Jesusvillanueva07 approved these changes
good job @Luisafernanda29

2022-09-20 13:13 UTC, hguzman approved these changes
Ok

2022-09-20 14:17 UTC, jvidesDev approved these changes
Nice job

2022-09-21 22:29 UTC, merged