new activity
hguzman/ADSO2558427 pull request #47
Opened 2022-09-16 15:31 UTC by Zhxrick

2022-09-18 00:59 UTC, LonelyWalker17 approved these changes
Good job @Zhxrick!!

2022-09-18 00:59 UTC, LonelyWalker17 commented on zharick_donado/hojadevida.md
> +
The links to the activities are missing.

2022-09-18 14:03 UTC, GoJhon commented
@LonelyWalker17 thank you for update the files. @Zhxrick please create a new branch for pull request. This pull request is into main from main.

2022-09-20 13:46 UTC, GoJhon requested changes
@LonelyWalker17 thank you for update the files. @Zhxrick please create a new branch for pull request. This pull request is into main from main.

2022-09-20 13:46 UTC, GoJhon commented on zharick_donado/hojadevida.md
> +
@Zhxrick nice logic and code, good job! remember, you need to add the exercises links in "Hoja de vida".

2022-10-24 21:15 UTC, closed without merging