Mi información básica
hguzman/ADSO2558427 pull request #51
Opened 2022-09-19 15:36 UTC by Cesar1520

Hello dear colleagues please review my work

2022-09-20 16:10 UTC, LonelyWalker17 commented on ejercicio.md
> +    While siguiente = "si" And totalRecaudo < 3000000
What is the function of the variable "siguiente"?

2022-09-20 16:12 UTC, LonelyWalker17 commented on ejercicio.md
> +        siguiente = InputBox("Alguien más va a donar?")
There could be conflicts here when executing this new InputBox. You already have one of these assigning above.

2022-09-20 16:16 UTC, LonelyWalker17 requested changes
You have too many bugs to fix. Please check your flowchart, it's a bit messy. The rest of the recommendations can be found in the comments.

2022-09-22 01:16 UTC, Luisafernanda29 approved these changes
Good job!

2022-09-23 20:29 UTC, LonelyWalker17 approved these changes
Well done @Cesar1520 .

2022-09-23 22:40 UTC, GoJhon approved these changes
@Cesar1520 Good job! keep it up!

2022-09-26 21:06 UTC, hguzman approved these changes
Ok

2022-09-26 21:07 UTC, merged