exercise
hguzman/ADSO2558427 pull request #7
Opened 2022-09-09 22:38 UTC by JuanCito16

Good afternoon, I send you today's exercise, I await your response.

2022-09-09 22:44 UTC, andresdtd requested changes
Please put the else in the diagram.

2022-09-12 20:50 UTC, JuanCito16 commented
Hello, the due changes have already been made in the diagram, I await your response, thank you

2022-09-13 01:01 UTC, juanhsd requested changes
Good evening! you developed your code well, but you are making mistakes in your diagram
Remember that we use the 'screen' to use the msgbox

2022-09-13 02:12 UTC, JuanCito16 commented
Good evening, the due changes have already been made to the diagram

2022-09-13 02:15 UTC, andresdtd approved these changes
I see your changes @JuanCito16 , good job!

2022-09-14 01:54 UTC, Luislemus0109 commented on juan_vides/ejercicio.md
> +            Total = Total + dinero
The same recommendation that I made to a colleague, for the variables it is more recommended that everything be in lowercase

2022-09-14 01:57 UTC, Luislemus0109 approved these changes
Good evening, good job just keep in mind the recommendation I gave you in the algorithm.

2022-09-14 15:14 UTC, GoJhon reviewed
Hello @JuanCito16, nice job. I have the same recomendation of @juanhsd.

2022-09-14 22:26 UTC, GoJhon approved these changes
Good job!

2022-09-15 02:51 UTC, juanhsd approved these changes

2022-09-15 03:06 UTC, closed without merging