single review
hguzman/ADSO2558427 pull request #8
Opened 2022-09-09 22:51 UTC by Cristian-pacheco

2022-09-10 00:37 UTC, GoJhon reviewed
Hi Cristian, you have a nice logic, but you need to fix your flowchart; in the decision c<=3000000, you forgot put "yes" and "no" on the flows, fix height on the flow and fix some variable.

2022-09-10 00:50 UTC, hguzman commented
@GoJhon excellent comment.
@Cristian-pacheco Please fix it.

2022-09-10 06:58 UTC, Luislemus0109 approved these changes
Good job!

2022-09-15 12:50 UTC, LonelyWalker17 approved these changes
Everything is fine in your code, not counting the broken links in the resume. I'll approve, but check your markdown file.

2022-09-15 12:50 UTC, LonelyWalker17 commented on cristianpacheco/codigo.md
> +     While c <= 2999999
I have seen this in a limited number of codes. Good logic.

2022-09-15 12:50 UTC, LonelyWalker17 commented on cristianpacheco/datos.md
> +- [ciclo mientras que en codigo](cristianpacheco\codigo.md)
The links are down. Please check your md

2022-09-17 18:16 UTC, GoJhon approved these changes
Hi @Cristian-pacheco, good job! I see your activity "buscador" and you have a good code. It's no necessary put a "sw" because you weren't use it, but it's alright. Keep it up!

2022-09-17 20:33 UTC, GoJhon requested changes
@Cristian-pacheco, please create a new branch for pull request. This pull request is into main from main.

2022-09-18 04:36 UTC, Jesusvillanueva07 approved these changes
good job. @Cristian-pacheco

2022-09-18 16:31 UTC, juanhsd approved these changes
Well done

2022-09-21 22:16 UTC, merged